# Generated by Django 6.0.4 on 2026-05-05 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_lastname', models.CharField(max_length=100)),
                ('child_firstname', models.CharField(max_length=100)),
                ('child_gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('father_lastname', models.CharField(max_length=100)),
                ('father_firstname', models.CharField(max_length=100)),
                ('father_profession', models.CharField(blank=True, max_length=100, null=True)),
                ('father_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('father_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_lastname', models.CharField(max_length=100)),
                ('mother_firstname', models.CharField(max_length=100)),
                ('mother_profession', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_address', models.CharField(blank=True, max_length=255, null=True)),
                ('act_number', models.CharField(max_length=100, unique=True)),
                ('registration_date', models.DateField()),
                ('registration_place', models.CharField(max_length=255)),
                ('civil_officer', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_acts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
