# Generated by Django 6.0.4 on 2026-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_birthact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthact',
            name='citizen',
        ),
    ]
