# Generated by Django 6.0.4 on 2026-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_certification_mayorsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
