# Generated by Django 6.0.4 on 2026-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_certification_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='stamp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
